spring:
  config:
    activate:
      on-profile: prod
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${prod.app.datasource.url}
    username: ${prod.app.datasource.username}
    password: ${prod.app.datasource.password}
    #name: druidDataSource
    druid:
      stat-view-servlet:
        enabled: ${prod.druid.view.enable}
        login-password: ${prod.druid.view.password}
        login-username: ${prod.druid.view.username}
        url-pattern: /druid/*
        allow:
      filters: stat,slf4j,wall
      max-active: 200
      initial-size: 5
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 84000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
  #redis
  redis:
    password: ${prod.app.redis.password}
    timeout: 30M
    port: ${prod.app.redis.port}
    host: ${prod.app.redis.host}
    lettuce:
      pool:
        max-active: 4
        min-idle: 0
        max-idle: 4
  #spring-session
  session:
    store-type: NONE
    timeout: 30M
    redis:
      namespace: ${cache.prefix}:${spring.config.activate.on-profile}:app:spring:session


logging:
  level:
    root: INFO
  file:
    name: /opt/logs/prog/dzt.idaymay.com/dzt-app-web.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 100MB
management:
  endpoint:
    env:
      enabled: false
    heapdump:
      enabled: false
  endpoints:
    web:
      ##面向外网，不暴露端点
      exposure:
        include: health
      path-mapping:
        health: ping
      base-path: /
swagger:
  show: false

wx:
  mp:
    appId: ${prod.wx.mp.appId}
    secret: ${prod.wx.mp.secret}
    token: ${prod.wx.mp.token}
    aesKey: ${prod.wx.mp.aesKey}
    config-storage:
      type: RedisTemplate
      key-prefix: wx
      redis:
        host: ${prod.app.redis.host}
        port: ${prod.app.redis.port}
        min-idle: 0
        maxActive: 4
        max-idle: 4
      http-client-type: HttpClient
      http-proxy-host:
      http-proxy-port:
      http-proxy-username:
      http-proxy-password:
config:
  openai:
    apiKey: ${prod.app.config.openai.apikey}
    associationRound: ${prod.app.config.openai.associationRound}
